### ISSUE TITLE
QUESTION 4 PARTIALLY CORRECT

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/phase-3-quiz-object-relational-mapping#1]
### Canvas Link

https://learning.flatironschool.com/courses/6559/quizzes/47496

### Concern

Question 4
1 / 1 pts
What are the steps needed to write a class that is mapped to a database table? Select all that apply.
1. Create a table with the same name as the class, but pluralized 
Exactly! If the class is called Cat, the table should be called cats.
  **2. Match the names of the table's columns to class variables**
  3. Create a table with the exact same name as the class 
  4. I don't know
  5. Match the names of the table's columns to the attributes of the class
So true! We need the columns and attributes to match, so that we know which data we're manipulating.

1 and 5 are correct but also is 2. See technically, class attributes are variables of the the class. **Both attributes and variables do not have to correspond, but usually do to columns on the database**. For instance having an attribute or property to hold the old values of the database for a certain record.

### Suggested Changes

Add option 2 as a correct option. 1, 2, and 5 are all correct. 1 and 5 are correct but also is 2. See technically, class attributes are variables of the the class. **Both attributes and variables do not have to correspond, but usually do to columns on the database**. For instance having an attribute or property to hold the old values of the database for a certain record.

**Comment by lizbur10** [comment]
Closing duplicate - issue transferred [here](https://github.com/learn-co-curriculum/python-p3-quiz-object-relational-mapping/issues/1)
